---
title: "Plots for SVM"
author: "Shy-Ann Moehamatdjalil"
date: "13-6-2021"
output: html_document
---

```{r}
x = c(0.5, 1, 3, 2, 4, 2.5, 1, 2, 4, 4, 4.5, 3.4)
y = c(2, 1.5, 4, 2, 4, 3, 4, 1, 3, 1, 2, 1.5)
colors = c("red", "red", "red","red", "red","red", "red", "blue", "blue", "blue", "blue", "blue")


plot(x, y, col = colors, xlim = c(0, 5), ylim = c(0, 5),
     pch = 20 ,cex = 2)


plot(x, y, col = colors, xlim = c(0, 5), ylim = c(0, 5),
     pch = 20 ,cex = 2)
abline(-0.5, 1)
text(0.5, 0.75, "Best Hyperplane")
```


```{r}
x = c(0.1, 0.3, 0.5, 0.8, 1, 1.3, 0.65, 0.7, 0.2, 0.3, 1, 
      1.8, 1.8, 1.9, 2.2, 2.5, 2.4, 2.8, 3, 2.5, 2.3,
      3.8, 4, 4.2, 4.5, 3.6, 4.1, 4.7, 3.7, 4.2, 4.5)
y = c(2.8, 3.0, 2.5, 3.5, 4, 3.3, 4, 3.2, 3.8, 4.3, 2.6,
      0.4, 0.6, 1.0, 1.8, 1.6, 1.75, 0.8, 1.5, 0.5, 1.4,
      3.5, 3.7, 4, 4.3, 3.8, 4.2, 3.3, 4.5, 3.3, 3.7)
colors = c("darkgreen", "darkgreen", "darkgreen", "darkgreen", "darkgreen", "darkgreen", "darkgreen", "darkgreen", "darkgreen", "darkgreen", "darkgreen", 
           "red", "red", "red", "red", "red", "red", "red", "red", "red", "red",
           "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue")

plot(x, y, col = colors, xlim = c(0, 5), ylim = c(0, 5),
     pch = 20 ,cex = 2)
abline(0, 1.4, col = "darkgreen", lwd = 2.5)
abline(5.8, -1, col = "blue", lwd = 2.5)
abline(1.8, 0.2, col = "red", lwd = 2.5)
```

